package:
  name: xstream
  version: '0.1.0'

source:
  git_url: https://github.com/dgursoy/xstream.git
  
build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - matplotlib

test:
  # Python imports
  imports:
    - xstream

about:
  home: http://xstream.rtfd.org
  license: BSD-3
  summary: 'Streaming data algorithms for x-ray tomography.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
